processed 18 tasks

init:
A: object(100)

task 1 'publish'. lines 8-115:
created: object(105)
written: object(104)

task 2 'run'. lines 117-117:
created: object(107)
written: object(106)

task 3 'run'. lines 119-123:
written: object(108)
deleted: object(107)

task 4 'run'. lines 125-125:
created: object(110)
written: object(109)

task 5 'run'. lines 127-127:
created: object(112), object(113)
written: object(110), object(111)

task 6 'run'. lines 129-133:
Error: Transaction Effects Status: Invalid Object Owned Argument. Object fake(112) is owned by object fake(113). Objects owned by other objects cannot be used as input arguments.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidChildObjectArgument(InvalidChildObjectArgument { child: fake(112), parent: fake(113) }), source: None, command: None } }

task 7 'run'. lines 135-135:
created: object(116)
written: object(115)

task 8 'run'. lines 137-140:
Error: Transaction Effects Status: Entry Argument Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>"), command: None } }

task 9 'run'. lines 142-142:
created: object(119)
written: object(118)

task 10 'run'. lines 144-144:
created: object(121)
written: object(120)

task 11 'run'. lines 146-149:
Error: Transaction Effects Status: Entry Argument Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>"), command: None } }

task 12 'run'. lines 151-151:
created: object(124)
written: object(123)

task 13 'run'. lines 153-156:
Error: Transaction Effects Status: Entry Argument Error. Error for argument at index 0: Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: InvalidObjectByValue }), source: Some("Immutable and shared objects cannot be passed by-value, violation found in argument 0"), command: None } }

task 14 'run'. lines 158-158:
created: object(127)
written: object(126)

task 15 'run'. lines 160-163:
Error: The transaction inputs contain duplicated ObjectRef's

task 16 'run'. lines 165-165:
created: object(130)
written: object(129)

task 17 'run'. lines 167-167:
Error: The transaction inputs contain duplicated ObjectRef's
